{{ $smbconfchecksum := tpl (.Files.Get "conf/smb.conf") . | sha256sum -}}
{{ $userschecksum := include "userstocreate" . | sha256sum -}}
{{ $scriptchecksum := tpl (.Files.Get "scripts/k8s.sh") . | sha256sum -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "samba4.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "samba4.name" . }}
    helm.sh/chart: {{ include "samba4.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    checksum/smbconf: {{ $smbconfchecksum }}
    checksum/users: {{ $userschecksum }}
{{ if .Values.image.lacksK8sScript -}}
    checksum/script: {{ $scriptchecksum }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "samba4.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "samba4.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/smbconf: {{ $smbconfchecksum }}
        checksum/users: {{ $userschecksum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cifs
              containerPort: 445
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - {{ .Values.livenessProbe.command | default "echo | smbclient -L 127.0.0.1" | quote }}
          readinessProbe:
            tcpSocket:
              port: cifs
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /secrets
            name: users
          - mountPath: /etc/samba/smb.conf
            name: smbconf
            subPath: smb.conf
{{- range .Values.persistence }}
  {{ .podVolumeMounts | toYaml | nindent 10 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: smbconf
        configMap:
          name: {{ include "samba4.fullname" . }}-smbconf
          defaultMode: 0644
          items:
          - key: smb.conf
            path: smb.conf
      - name: users
        secret:
          secretName: {{ include "samba4.fullname" . }}-users
          defaultMode: 0600
{{- range .Values.persistence }}
  {{ .deploymentVolumes | toYaml | nindent 6 }}
{{- end }}
