{{- range .Values.persistence }}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
{{- with $ }}
    app.kubernetes.io/name: {{ include "samba4.name" . }}
    helm.sh/chart: {{ include "samba4.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
  name: {{ .name }}
spec:
{{ .pvSpec | toYaml | nindent 2}}
{{- end }}